clear; clc; close all;

%% Parameters
Isc = 2.0;
I0  = 5.0e-10;
Ad  = 39.8;
Rs  = 0.04;
Rp  = 8.0;

%% Voltage sweep
V = linspace(0,0.6,6001);

%% Ideal model
I_ideal = Isc - I0.*(exp(Ad.*V) - 1);
I_ideal = min(max(I_ideal,0),Isc);
P_ideal = V .* I_ideal;

%% Non-ideal model
I_nonideal = zeros(size(V));

tol = 1e-8;
maxIter = 50;

for k = 1:length(V)

    Vk = V(k);

    if k == 1
        I = Isc;
    else
        I = I_nonideal(k-1);
    end

    for iter = 1:maxIter

        Vj = Vk + I*Rs;

        F = I - Isc ...
            + I0*(exp(Ad*Vj) - 1) ...
            + Vj/Rp;

        dF = 1 ...
            + I0*exp(Ad*Vj)*Ad*Rs ...
            + Rs/Rp;

        Inew = I - F/dF;

        if abs(Inew-I) < tol
            I = Inew;
            break
        end

        I = Inew;

    end

    I_nonideal(k) = min(max(I,0),Isc);

end

P_nonideal = V .* I_nonideal;

%% Maximum-power points
[Pmpp_ideal,idxIdeal] = max(P_ideal);

Vmpp_ideal = V(idxIdeal);
Impp_ideal = I_ideal(idxIdeal);

[Pmpp_nonideal,idxNonideal] = max(P_nonideal);

Vmpp_nonideal = V(idxNonideal);
Impp_nonideal = I_nonideal(idxNonideal);

reduction_percent = ...
    100*(Pmpp_ideal-Pmpp_nonideal)/Pmpp_ideal;

fprintf('\nIdeal MPP\n');
fprintf('Vmpp = %.4f V\n',Vmpp_ideal);
fprintf('Impp = %.4f A\n',Impp_ideal);
fprintf('Pmpp = %.4f W\n',Pmpp_ideal);

fprintf('\nNon-ideal MPP\n');
fprintf('Vmpp = %.4f V\n',Vmpp_nonideal);
fprintf('Impp = %.4f A\n',Impp_nonideal);
fprintf('Pmpp = %.4f W\n',Pmpp_nonideal);

fprintf('\nMPP reduction = %.2f %%\n',reduction_percent);

%% Plot limits
xmax = 0.57;

%% Colors
idealColor    = [0.95 0.35 0.20];
nonidealIV    = [0.20 0.70 0.45];
nonidealPV    = [0.20 0.45 0.85];

%% Figure
fig = figure( ...
    'Color','w', ...
    'Position',[100 100 760 660]);

tl = tiledlayout(2,1, ...
    'TileSpacing','compact', ...
    'Padding','compact');

%% Main title
title(tl, ...
    'Ideal and Non-Ideal Single-Diode PV Cell Characteristics', ...
    'FontWeight','bold', ...
    'FontSize',12);
%% (a) I-V characteristics
ax1 = nexttile;

plot(V,I_ideal, ...
    'Color',idealColor, ...
    'LineWidth',1.6);
hold on;

plot(V,I_nonideal, ...
    'Color',nonidealIV, ...
    'LineWidth',1.6);

plot(Vmpp_ideal,Impp_ideal, ...
    'ko', ...
    'MarkerFaceColor','k', ...
    'MarkerSize',4, ...
    'HandleVisibility','off');

plot(Vmpp_nonideal,Impp_nonideal, ...
    'ko', ...
    'MarkerFaceColor','k', ...
    'MarkerSize',4, ...
    'HandleVisibility','off');

text( ...
    Vmpp_ideal+0.012, ...
    Impp_ideal-0.10, ...
    sprintf('X %.4f\nY %.4f', ...
    Vmpp_ideal,Impp_ideal), ...
    'FontSize',9, ...
    'BackgroundColor','w', ...
    'EdgeColor',[0.65 0.65 0.65], ...
    'Margin',5);

text( ...
    Vmpp_nonideal-0.090, ...
    Impp_nonideal-0.12, ...
    sprintf('X %.4f\nY %.4f', ...
    Vmpp_nonideal,Impp_nonideal), ...
    'FontSize',9, ...
    'BackgroundColor','w', ...
    'EdgeColor',[0.65 0.65 0.65], ...
    'Margin',5);

ylabel('Current (A)');
title('(a) Current-Voltage (I-V) Characteristics');

legend( ...
    'Ideal', ...
    'Non-ideal', ...
    'Location','southwest');

xlim([0 xmax]);
ylim([0 2.2]);

grid on;
box on;

%% (b) P-V characteristics
ax2 = nexttile;

plot(V,P_ideal, ...
    'Color',idealColor, ...
    'LineWidth',1.6);
hold on;

plot(V,P_nonideal, ...
    'Color',nonidealPV, ...
    'LineWidth',1.6);

plot(Vmpp_ideal,Pmpp_ideal, ...
    'ko', ...
    'MarkerFaceColor','k', ...
    'MarkerSize',4, ...
    'HandleVisibility','off');

plot(Vmpp_nonideal,Pmpp_nonideal, ...
    'ko', ...
    'MarkerFaceColor','k', ...
    'MarkerSize',4, ...
    'HandleVisibility','off');

text( ...
    Vmpp_ideal+0.010, ...
    Pmpp_ideal+0.015, ...
    sprintf('X %.4f\nY %.4f', ...
    Vmpp_ideal,Pmpp_ideal), ...
    'FontSize',9, ...
    'BackgroundColor','w', ...
    'EdgeColor',[0.65 0.65 0.65], ...
    'Margin',5);

text( ...
    Vmpp_nonideal-0.105, ...
    Pmpp_nonideal-0.095, ...
    sprintf('X %.4f\nY %.4f', ...
    Vmpp_nonideal,Pmpp_nonideal), ...
    'FontSize',9, ...
    'BackgroundColor','w', ...
    'EdgeColor',[0.65 0.65 0.65], ...
    'Margin',5);

xlabel('Voltage (V)');
ylabel('Power (W)');
title('(b) Power-Voltage (P-V) Characteristics');

legend( ...
    'Ideal', ...
    'Non-ideal', ...
    'Location','northwest');

xlim([0 xmax]);
ylim([0 1.0]);

grid on;
box on;

linkaxes([ax1 ax2],'x');

title(tl, ...
    'Ideal and Non-Ideal PV Cell Characteristics', ...
    'FontWeight','bold');

%% Export
exportgraphics( ...
    fig, ...
    'Figure8_Ideal_Nonideal_PV.png', ...
    'Resolution',600);