clear; clc; close all;

fig = figure( ...
    'Color','w', ...
    'Position',[100 100 900 520]);

ax = axes('Position',[0 0 1 1]);
axis(ax,[0 10 0 6]);
axis off;
hold on;

%% Coordinates
yTop = 4.5;
yBot = 1.3;

xLeft  = 1.5;
xRp    = 3.5;
xDiode = 5.0;
xRs1   = 6.2;
xRs2   = 7.4;
xLoad  = 8.5;

%% Main wires
plot([xLeft xRs1],[yTop yTop],'k','LineWidth',2);
plot([xLeft xLoad],[yBot yBot],'k','LineWidth',2);

%% Current source
plot([xLeft xLeft],[yBot 2.1],'k','LineWidth',2);
plot([xLeft xLeft],[3.7 yTop],'k','LineWidth',2);

rectangle( ...
    'Position',[xLeft-0.35 2.1 0.7 1.6], ...
    'Curvature',[1 1], ...
    'EdgeColor','k', ...
    'LineWidth',2);

quiver( ...
    xLeft,2.45,0,0.75,0, ...
    'Color','k', ...
    'LineWidth',1.8, ...
    'MaxHeadSize',0.9);

text( ...
    xLeft-0.75,2.9,'I_{SC}', ...
    'FontSize',14, ...
    'Interpreter','tex');

%% Shunt resistance Rp
plot([xRp xRp],[yTop 3.85],'k','LineWidth',2);
plot([xRp xRp],[2.0 yBot],'k','LineWidth',2);

zigzagVertical(xRp,2.0,3.85,0.22);

text( ...
    xRp+0.35,2.9,'R_p', ...
    'FontSize',14, ...
    'Interpreter','tex');

%% Diode D
plot([xDiode xDiode],[yTop 3.45],'k','LineWidth',2);

plot( ...
    [xDiode-0.38 xDiode+0.38], ...
    [3.15 3.15], ...
    'k','LineWidth',2);

plot( ...
    [xDiode-0.38 xDiode], ...
    [3.15 2.50], ...
    'k','LineWidth',2);

plot( ...
    [xDiode+0.38 xDiode], ...
    [3.15 2.50], ...
    'k','LineWidth',2);

plot([xDiode xDiode],[3.45 3.15],'k','LineWidth',2);

plot( ...
    [xDiode-0.38 xDiode+0.38], ...
    [2.30 2.30], ...
    'k','LineWidth',2);

plot([xDiode xDiode],[2.50 2.30],'k','LineWidth',2);
plot([xDiode xDiode],[2.30 yBot],'k','LineWidth',2);

text( ...
    xDiode+0.48,2.75,'D', ...
    'FontSize',14);

%% Series resistance Rs
plot([xRs1 xRs1+0.25],[yTop yTop],'k','LineWidth',2);

zigzagHorizontal( ...
    xRs1+0.25, ...
    xRs2-0.25, ...
    yTop, ...
    0.18);

plot([xRs2-0.25 xRs2],[yTop yTop],'k','LineWidth',2);

text( ...
    (xRs1+xRs2)/2-0.15, ...
    yTop+0.45, ...
    'R_s', ...
    'FontSize',14, ...
    'Interpreter','tex');

%% Load
plot([xRs2 xLoad],[yTop yTop],'k','LineWidth',2);
plot([xLoad xLoad],[yTop 3.8],'k','LineWidth',2);
plot([xLoad xLoad],[2.0 yBot],'k','LineWidth',2);

zigzagVertical(xLoad,2.0,3.8,0.22);

text( ...
    xLoad+0.35,2.9,'Load', ...
    'FontSize',14);

%% Ground
xG = xDiode;

plot([xG xG],[yBot 0.8],'k','LineWidth',2);

plot( ...
    [xG-0.45 xG+0.45], ...
    [0.8 0.8], ...
    'k','LineWidth',2);

plot( ...
    [xG-0.30 xG+0.30], ...
    [0.6 0.6], ...
    'k','LineWidth',2);

plot( ...
    [xG-0.15 xG+0.15], ...
    [0.4 0.4], ...
    'k','LineWidth',2);

%% Junction nodes
plot( ...
    [xLeft xRp xDiode], ...
    [yTop yTop yTop], ...
    'ko', ...
    'MarkerFaceColor','k', ...
    'MarkerSize',5);

plot( ...
    [xLeft xRp xDiode], ...
    [yBot yBot yBot], ...
    'ko', ...
    'MarkerFaceColor','k', ...
    'MarkerSize',5);

%% Title
title( ...
    'Single-Diode PV Equivalent Circuit', ...
    'FontWeight','bold', ...
    'FontSize',15);

%% Export
exportgraphics( ...
    fig, ...
    'Figure1_Single_Diode_PV_Circuit.png', ...
    'Resolution',600);

exportgraphics( ...
    fig, ...
    'Figure1_Single_Diode_PV_Circuit.pdf', ...
    'ContentType','vector');

%% Local functions
function zigzagVertical(x,y1,y2,amp)

    n = 8;
    ys = linspace(y1,y2,2*n+1);
    xs = x*ones(size(ys));

    for k = 2:length(xs)-1
        if mod(k,2)==0
            xs(k) = x + amp;
        else
            xs(k) = x - amp;
        end
    end

    plot(xs,ys,'k','LineWidth',2);
end

function zigzagHorizontal(x1,x2,y,amp)

    n = 8;
    xs = linspace(x1,x2,2*n+1);
    ys = y*ones(size(xs));

    for k = 2:length(ys)-1
        if mod(k,2)==0
            ys(k) = y + amp;
        else
            ys(k) = y - amp;
        end
    end

    plot(xs,ys,'k','LineWidth',2);
end